version: "3.1"
services:
  python:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bottlesite_container
    ports:
      - 80:80
    volumes:
      - ./:/app


